spring.application.name=ultimateflange
# Disable security completely
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Server
server.port=${PORT:8080}

spring.profiles.active=${ENV:dev}
